
export const BACKSTAGE_PASSES_SELLIN_THRESHOLD_1: number = 5;
export const BACKSTAGE_PASSES_SELLIN_THRESHOLD_2: number = 10;
export const BACKSTAGE_PASSES_QUALITY_ZERO: number = 0;
export const BACKSTAGE_PASSES_QUALITY_INCREASE_1: number = 3;
export const BACKSTAGE_PASSES_QUALITY_INCREASE_2: number = 2;